### ISSUE TITLE
Class 'object' not found

### ISSUE THREAD

**Issue by tblion** [NextDom/plugin-Meross#16]
## Description
Salut, quand je lance le plugin, j'ai "Class 'object' not found" qui s'affiche.

J'ai accès a la configuration du plugin et j'ai bien rentré mes identifiants etc...
## Etapes à reproduire (pour les bugs)

1.Aller dans Plugin
2.Protocole
3.Meross

## Environnement:

* **Jeedom 4.0.21**:
* **DIY**:
* **Version 65d638791fbe9a3439de**:

Je n'arrive pas a trouver des logs

![image](https://user-images.githubusercontent.com/4974964/66715741-0b937a00-edc7-11e9-9f0f-c6683016e6d2.png)

**Comment by Kiyeko** [comment]
Bonsoir, j'ai exactement le même problème
Version Jeedom : 4.0.24
Branche : V4-stable
Système : RPI 3 B
Raspbian GNU/Linux 9 (stretch) 32bits (armv7l)

**Comment by Kiyeko** [comment]
Quelqu'un pourrait-il rendre ce plugin compatible V4 ou indiquer la marche à suivre SVP?
Merci

**Comment by tblion** [comment]
Apparement il faut remplacer Object par JeeObject dans les sources. J'ai pas eu le temps de tester encore

**Comment by Kiyeko** [comment]
> Apparement il faut remplacer Object par JeeObject dans les sources. J'ai pas eu le temps de tester encore

Hello, est ce que tu as essayé? Est ce que ça marche et faut-il le faire sur toutes les sources?
