### ISSUE TITLE
Erreur script meross.py sur Jeedom 4

### ISSUE THREAD

**Issue by xtab17** [NextDom/plugin-Meross#20]
## Description
Le log Jeedom renvoie régulièrement (tache com) l'erreur suivante mais pour autant les données de mes prise meross sont bien renvoyée.
meross.sh: 22: meross.sh: [[: not found

## Etapes à reproduire (pour les bugs)
1 Exécution du script en ligne  :
 sudo sh meross.sh --email xxx --password xxx --refresh --show
2. le retour du script et bien un json mais qui fini par cette erreur 

{
    "1804176849719629xxxxxxxxx": {
        "consumption": [],
        "consumption_yesterday": 0,
        "firmversion": "1.1.7",
        "hardversion": "1.0.0",
        "ip": "192.168.0.9",
        "mac": "34:xxxxxxxx,
        "name": "Multiprise",
        "online": 1,
        "onoff": [
            1,
            0,
            0,
            0,
            0,
            1
        ],
        "power": "-1",
        "type": "mss425f",
        "uuid": "180417684971xxxxxxxx"
    },
    "18090101420823251xxxxxxxx": {
        "consumption": [],
        "consumption_yesterday": 0.059,
        "firmversion": "2.1.12",
        "hardversion": "2.0.0",
        "ip": "192.168.0.48",
        "mac": "34:xxxxxxxx",
        "name": "Prise Centrale",
        "online": 1,
        "onoff": [
                      0
        ],
        "power": 0.0,
        "type": "mss310",
        "uuid": "180901014xxxxxxxx"
    },
    "18090134901xxxxxxxx": {
        "consumption": [],
        "consumption_yesterday": 0.086,
        "firmversion": "2.1.12",
        "hardversion": "2.0.0",
        "ip": "192.168.0.16",
        "mac": "34:xxxxxxxx",
        "name": "Salon 1",
        "online": 1,
        "onoff": [
            0
        ],
        "power": 0.0,
        "type": "mss310",
        "uuid": "1809013xxxxxxxx"
    },
    "180901350xxxxxxxx": {
        "consumption": [],
        "consumption_yesterday": 0,
        "firmversion": "",
        "hardversion": "",
        "ip": "",
        "mac": "",
        "name": "luminaire",
        "online": "",
        "onoff": [],
        "power": "-1",
        "type": "",
        "uuid": "1809013xxxxxxxx"
    },
    "180901710xxxxxxxx": {
        "consumption": [],
        "consumption_yesterday": 0.155,
                "firmversion": "2.1.12",
        "hardversion": "2.0.0",
        "ip": "192.168.0.28",
        "mac": "xxxxxxxx",
        "name": "Cuisine 1",
        "online": 1,
        "onoff": [
            0
        ],
        "power": 0.0,
        "type": "mss310",
        "uuid": "18090171087xxxxxxxx"
    }
}
meross.sh: 22: meross.sh: [[: not found

## Contexte:
Est-ce lié au fait que parmi les périphériques meross je dispose d'une prise extérieur mss620 qui n'est pas reconnu et n'apparait pas dans la réponse json ? 

## Environnement:

* **Version NextDom**: 4.0.35
* **Plateforme**: Debian Burster 10
* **Version du Plugin**:

**Comment by slobberbone** [comment]
@xtab17  NextDom version 4.0.35 ? je crois que ca n'existe pas ;)

**Comment by slobberbone** [comment]
Ta version de bash devrait comprendre cette instruction ...

**Comment by xtab17** [comment]
En fait, c’est une install du plugin Meross faite sur Jeedom 4.0.35.

**Comment by Astral0** [comment]
Normalement c'est corrigé avec la version de ce soir.
Tu peux confirmer ?

**Comment by slobberbone** [comment]
@xtab17

**Comment by xtab17** [comment]
Je suis en déplacement. Je regarde ce week-end

**Comment by xtab17** [comment]
@Astral0 
Suite Update , plus d'erreur , merci je confirme c'est corrigé.
